camel:
  component:
    servlet:
      mapping:
        contextPath: /gatewaygroup/api/*
opencagedata:
  api:
    key: ${OPENCAGEDATA_API_KEY}
    uri: ${OPENCAGEDATA_API_URI:https://api.opencagedata.com/geocode/v1/json?limit=1&bridgeEndpoint=true}
